name: flappy_bird_online
version: 1.0.0

description: A WebSocket server for Flappy Bird online multiplayer.
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  shelf: ^1.4.0
  shelf_web_socket: ^1.0.3
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^3.0.0
